### ISSUE TITLE
Error in building image

### ISSUE THREAD

**Issue by lohnsonok** [vtorres/gitpod-flutter#3]
building base image

initializing base image context
UGit operations complete                       location=/workspace/init
running base image build
Step 1/33 : FROM gitpod/workspace-full:latest
latest: Pulling from gitpod/workspace-full
Digest: sha256:abaaf2123993b85b8614fdadc486fcfae50e01932739949af683e55921f81a9d
Status: Image is up to date for gitpod/workspace-full:latest
 ---> 85086b7a9c6a
Step 2/33 : LABEL maintainer="vitortorresvt@gmail.com"
 ---> Using cache
 ---> 9bdc6060ac63
Step 3/33 : USER root
 ---> Using cache
 ---> 941a48345fb6
Step 4/33 : RUN apt-get update -y
 ---> Using cache
 ---> c4f5bc8a36da
Step 5/33 : RUN apt-get install -y gcc make build-essential wget curl unzip apt-utils xz-utils libkrb5-dev gradle libpulse0 android-tools-adb android-tools-fastboot
 ---> Using cache
 ---> 083c968c355b
Step 6/33 : RUN apt remove --purge openjdk-*-jdk
 ---> Using cache
 ---> 8b9e729baf07
Step 7/33 : RUN apt-get install -y openjdk-8-jdk
 ---> Using cache
 ---> 8be5b871dd7b
Step 8/33 : USER gitpod
 ---> Using cache
 ---> cbb75361c3cc
Step 9/33 : ENV JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
 ---> Using cache
 ---> 65552e8a9b9b
Step 10/33 : ENV ANDROID_HOME="/home/gitpod/.android"
 ---> Using cache
 ---> 3304d867101f
Step 11/33 : ENV ANDROID_SDK_URL="https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip"
 ---> Using cache
 ---> c76fa50edb5f
Step 12/33 : ENV ANDROID_SDK_ARCHIVE="${ANDROID_HOME}/archive"
 ---> Using cache
 ---> 2b9e0ae70b91
Step 13/33 : ENV ANDROID_STUDIO_PATH="/home/gitpod/"
 ---> Using cache
 ---> 52f360980c3c
Step 14/33 : RUN cd "${ANDROID_STUDIO_PATH}"
 ---> Using cache
 ---> a5d58c762842
Step 15/33 : RUN wget -qO android_studio.zip https://dl.google.com/dl/android/studio/ide-zips/3.3.0.20/android-studio-ide-182.5199772-linux.zip
 ---> Using cache
 ---> 795ce1ecc56f
Step 16/33 : RUN unzip android_studio.zip
 ---> Using cache
 ---> 3259b7a23729
Step 17/33 : RUN rm -f android_studio.zip
 ---> Using cache
 ---> 31d5e6a753eb
Step 18/33 : RUN mkdir -p "${ANDROID_HOME}"
 ---> Using cache
 ---> fe74c13b7d0c
Step 19/33 : RUN touch $ANDROID_HOME/repositories.cfg
 ---> Using cache
 ---> 88d9e64efa28
Step 20/33 : RUN wget -q "${ANDROID_SDK_URL}" -O "${ANDROID_SDK_ARCHIVE}"
 ---> Using cache
 ---> ead807341ee6
Step 21/33 : RUN unzip -q -d "${ANDROID_HOME}" "${ANDROID_SDK_ARCHIVE}"
 ---> Using cache
 ---> 386e94a8b766
Step 22/33 : RUN echo y | "${ANDROID_HOME}/tools/bin/sdkmanager" "platform-tools" "platforms;android-28" "build-tools;28.0.3"
 ---> Using cache
 ---> edf1cfdfd3f4
Step 23/33 : RUN rm "${ANDROID_SDK_ARCHIVE}"
 ---> Using cache
 ---> 0c26f66a1482
Step 24/33 : ENV FLUTTER_HOME="/home/gitpod/flutter"
 ---> Using cache
 ---> 0b1090e9f41d
Step 25/33 : RUN git clone https://github.com/flutter/flutter $FLUTTER_HOME
 ---> Using cache
 ---> ad52386e61e6
Step 26/33 : RUN $FLUTTER_HOME/bin/flutter channel master
 ---> Using cache
 ---> baa5cea9d507
Step 27/33 : RUN $FLUTTER_HOME/bin/flutter upgrade
 ---> Using cache
 ---> a79f18ba76dc
Step 28/33 : RUN $FLUTTER_HOME/bin/flutter precache
 ---> Using cache
 ---> ef1ec975d193
Step 29/33 : RUN $FLUTTER_HOME/bin/flutter config --enable-web --no-analytics
 ---> Using cache
 ---> 79bf5150623b
Step 30/33 : RUN yes "y" | $FLUTTER_HOME/bin/flutter doctor --android-licenses -v
 ---> Running in 7f58e8057646
Android sdkmanager not found. Update to the latest Android SDK and ensure that the cmdline-tools are installed to resolve this.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      AndroidLicenseValidator.runLicenseManager (package:flutter_tools/src/android/android_workflow.dart:421:7)
#2      Doctor.diagnose (package:flutter_tools/src/doctor.dart:295:38)
#3      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:47)
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1275:12)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1126:27)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
<asynchronous suspension>
#11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>

Error: build failed: cannot build base image: The command '/bin/sh -c yes "y" | $FLUTTER_HOME/bin/flutter doctor --android-licenses -v' returned a non-zero code: 1

**Comment by MeloHenrique** [comment]
Same error.
Any suggestion to fix it?

**Comment by MeloHenrique** [comment]
@lohnsonok I've made some pull requests, and now it's working. Let me know if something isn't working.
